"""
Django settings for openapply_backend project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f0g5z)qh1-id9%5$94ag*^-4-d1fb#!7=9t^pv$wvp$28)^6u@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rag',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'openapply_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'openapply_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

import os
from dotenv import load_dotenv

load_dotenv()

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
OPENAI_MODEL = os.getenv("OPENAI_MODEL")
# 兼容 DashScope 等 OpenAI-compatible 服务；不配置时使用 OpenAI 默认地址。
OPENAI_BASE_URL = os.getenv("OPENAI_BASE_URL")
EMBEDDING_MODEL_ID = os.getenv(
    "EMBEDDING_MODEL_ID",
    "BAAI/bge-base-zh-v1.5",
)

EMBEDDING_MODEL_PATH = Path(
    os.getenv(
        "EMBEDDING_MODEL_PATH",
        BASE_DIR / "models" / "bge-base-zh-v1.5",
    )
)

RAG_DATA_DIR = BASE_DIR / "data"
RAG_VECTOR_DIR = BASE_DIR / "data" / "vector_store"

BM25_TOP_K = 20
VECTOR_TOP_K = 20
RRF_K = 60
RRF_CANDIDATE_TOP_K = 30
FINAL_CONTEXT_TOP_K = 12
ANSWER_DISPLAY_TOP_K = 5
TASK_MEMORY_TTL_HOURS = 6
RERANK_BACKEND = os.getenv("RERANK_BACKEND", "weighted")

RERANK_API_KEY = os.getenv(
    "RERANK_API_KEY",
    OPENAI_API_KEY,
)

RERANK_API_URL = os.getenv(
    "RERANK_API_URL",
    "",
)

RERANK_MODEL = os.getenv(
    "RERANK_MODEL",
    "qwen3-rerank",
)

RERANK_CANDIDATE_TOP_K = int(
    os.getenv("RERANK_CANDIDATE_TOP_K", "20")
)

RERANK_TIMEOUT_SECONDS = float(
    os.getenv("RERANK_TIMEOUT_SECONDS", "10")
)

if RERANK_BACKEND == "qwen" and not RERANK_API_URL:
    raise RuntimeError(
        "RERANK_API_URL is required when RERANK_BACKEND=qwen"
    )